services:
  postgres:
    image: postgres:16-alpine
    container_name: ezauth-postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespwd
      POSTGRES_DB: ezauthdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
