site_name: EzAuth
site_description: Simple and easy to use authentication library for Golang.
repo_url: https://github.com/josuebrunel/ezauth
repo_name: josuebrunel/ezauth

docs_dir: doc_src
site_dir: docs

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Configuration: configuration.md
  - Usage:
      - As a Library: library.md
      - Standalone Service: standalone.md
  - Reference:
      - API Endpoints: api-endpoints.md
      - Architecture: architecture.md
      - Handler: references/handler.md
      - Service: references/service.md
      - Repository: references/repository.md
  - Examples:
      - Go Server: examples/go-server.md
      - Javascript Client: examples/javascript-client.md
