package models

const (
	TableUser               = "ezauth_users"
	TableToken              = "ezauth_tokens"
	TableWebauthnCredential = "ezauth_webauthn_credentials"
	TableWebauthnChallenge  = "ezauth_webauthn_challenges"
	ColumnEmail             = "email"
	ColumnUsername          = "username"
	ColumnPasswordHash      = "password_hash"
	ColumnProvider          = "provider"
	ColumnProviderID        = "provider_id"
	ColumnEmailVerified     = "email_verified"
	ColumnAppMetadata       = "app_metadata"
	ColumnUserMetadata      = "user_metadata"
	ColumnFirstName         = "first_name"
	ColumnLastName          = "last_name"
	ColumnLastActiveAt      = "last_active_at"
	ColumnLastLoginAt       = "last_login_at"
	ColumnLocale            = "locale"
	ColumnTimezone          = "timezone"
	ColumnEmailVerifiedAt   = "email_verified_at"
	ColumnPhone             = "phone"
	ColumnPhoneVerified     = "phone_verified"
	ColumnIsActive          = "is_active"
	ColumnAvatarURL         = "avatar_url"
	ColumnNickname          = "nickname"
	ColumnRoles             = "roles"
	ColumnMfaSecret         = "mfa_secret"
	ColumnMfaEnabled        = "mfa_enabled"
	ColumnCreatedAt         = "created_at"
	ColumnUpdatedAt         = "updated_at"
	ColumnUserID            = "user_id"
	ColumnToken             = "token"
	ColumnTokenType         = "token_type"
	ColumnExpiresAt         = "expires_at"
	ColumnRevoked           = "revoked"
	ColumnMetadata          = "metadata"

	ColumnCredentialID    = "credential_id"
	ColumnPublicKey       = "public_key"
	ColumnSignCount       = "sign_count"
	ColumnTransports      = "transports"
	ColumnAttestationType = "attestation_type"
	ColumnName            = "name"
	ColumnData            = "data"
	ColumnLastUsedAt      = "last_used_at"
	ColumnSessionKey      = "session_key"
	ColumnChallengeType   = "challenge_type"
)
